project:
  name: "olist_late_orders_prediction"
  version: "0.1.0"

paths:
  data_dir: "data"
  models_dir: "models"
  logs_dir: "logs"

  city_mapping: "data/geo_city_cleaning_mapping.csv"
  preprocessor: "models/preprocessor.joblib"
  model: "models/best_model.joblib"
  feature_list: "models/feature_list.csv"

model:
  name: "hist_gradient_boosting"
  version: "1"
  registered_name: "olist_late_order_model"
  stage: "Staging"
  
mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "olist_late_orders"